version: '2'
services:
    website:
        image: kdeloach/septa-viz
        build:
            context: ./src/app
        volumes:
            - ./data:/usr/data
            - ./static:/usr/share/static
            - ./src/app:/usr/src
        env_file: .env

    collect:
        image: kdeloach/septa-viz
        build:
            context: ./src/app
        volumes:
            - ./data:/usr/data
            - ./static:/usr/share/static
            - ./src/app:/usr/src
        env_file: .env
        restart: always
        command: collect
