version: '2'
services:
    app:
        image: septaviz-backend
        build:
            context: src/backend
        volumes:
            - $PWD/src:/usr/src
            - $PWD/scripts:/usr/src/scripts
            - $PWD/data:/usr/data
        ports:
            - "8000:8000"
        command: /usr/src/backend/server.py 0.0.0.0 8000
